services:

    frontend:
        build:
            context: ../FE
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
    backend:
        build:
            context: ../BE
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - redis

    redis:
        image: redis:latest
        container_name: redis
        command: redis-server --requirepass "chibbol2023"
        ports:
            - "6380:6380"

