services:
  spring:
    build:
      context: ../BE
      dockerfile: Dockerfile
    container_name: spring
    ports:
      - '8080:8080'
    depends_on:
      - redis
    environment:
      - TZ=Asia/Seoul

  react:
    build:
      context: ../FE
      dockerfile: Dockerfile
    container_name: react
    ports:
      - '3000:3000'
    depends_on:
      - spring
