# 1. open vidu 컨테이너 실행
# 2. nginx 컨테이너 실행
# 3. react 도커 이미지 빌드
# 4. react 도커 컨테이너 실행
# 5. spring 도커 이미지 빌드
# 6. spring 도커 컨테이너 실행
# 7. maria DB 컨테이너 실행
# 8. redis 컨테이너 실행

services:
    nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
    frontend:
        build:
            context: ../FE
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
    backend:
        build:
            context: ../BE
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        command: 
        depends_on:
            - mariadb
            - redis
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=84TRLiiFWJ
            - MYSQL_DATABASE=S09P12D206
            - MYSQL_USER=S09P12D206
            - HIKARI_MAXIMUM_POOL_SIZE=3
            - HIKARI_CONNECTION_TIMEOUT=30000 
        ports:
            - "3306:3306"
    redis:
        image: redis:latest
        container_name: redis
        command: redis-server --requirepass "chibbol2023"
        ports:
            - "6380:6380"

